# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# build with latest available ubuntu version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    nodejs: "14"
  jobs:
    pre_install:
      - python -m pip install jupyter jupyter-packaging jupyterlab

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
